### ISSUE TITLE
Code expects tab delimited file

### ISSUE THREAD

**Issue by jcorbs** [millarkm/Valant#3]
The data file provided is not tab delimited, it has carriage returns at the end of each line.  Why does the code expect a tab delimitation? Did you run this code on MarketingDataFile.txt directly, or create your own file?

**Comment by millarkm** [comment]
Thanks for the feedback Josh. 
I used this file during development. I just compared the GitHub version with my local and they are the same. The fields are tab delimited and the records (each line) are terminated with CR (standard for Windows text files). Still runs fine locally here...however, thinking it through...It's possible my Git config changed the line ends to be compatible with Linux (maybe that's a default setup). I don't have a lot of Git experience but did see config options to address this issue. This probably contains the answer we need once we confirm your environment: https://help.github.com/articles/dealing-with-line-endings/

Are you running on Windows, Linux or OS X?

My file shows invisible chars of tab delimited, CR terminated records.
![marketing data invisible chars](https://cloud.githubusercontent.com/assets/13059725/18331666/8e1b0a0c-7515-11e6-8109-f2917b7ca0ed.jpg)

**Comment by jcorbs** [comment]
Hrm, interesting. Here is the untouched file.
[MarketingDataFile.txt](https://github.com/millarkm/Valant/files/460559/MarketingDataFile.txt)

I have a Win7 box at home, Win10 at work. That file looks nothing like the one you screen shotted above, I wonder if there was a mixup somewhere.

**Comment by millarkm** [comment]
[I added a comment last night but don't see it this morning, I'll re-add]
[Uploaded copy of MarketingDataFile.txt](https://github.com/millarkm/Valant/files/462123/MarketingDataFile.txt)
I added a branch with a .gitattributes and set my global line end config to be compatible with Windows files. If this attached file is properly viewable by you then maybe the branch will have applied the fix correctly.
